### ISSUE TITLE
Introduce system metrics

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#493]
Let's introduce the concept of system metrics to Conbench.

For better debuggability, for understanding the current system better, and for being able to health-monitor production instances.

Pick a library for providing a Prometheus metrics exporter endpoint. Start implementing basic counters so that we can measure HTTP request rate and error response rate for individual endpoints. Also start implementing basic timers so that we better understand expected timings around specific HTTP endpoints.

This relates to how we run the Flask app: currently we run N processes, each process processing at most one HTTP request at any given time. Should each process manage and export its own set of metrics? That would be quite a bit of overhead: for example in Kubernetes a single container would then expose N metrics endpoints that need to be scraped.

Maybe it's a good time to change the worker/deployment model where we use gunicorn's threaded workers. Per gunicorn instance we could run one process with N (actual) threads, each thread then processing at most one HTTP request at any given time.

**Comment by austin3dickey** [comment]
I had the idle thought the other day that we could publish these kinds of metrics to a Conbench server itself. It would be a good source of training data for when we're testing alerting algorithms, etc. It could also help us ensure we don't introduce changes that drastically slow down the API.

**Comment by jgehrcke** [comment]
> we could publish these kinds of metrics to a Conbench server itself

Interesting!

I have a very canonical stack in mind here that gets us to building useful dashboards right away. The typical flow is that the application provides a scrape endpoint using the Prometheus format (that need to be _pulled_ from, periodically). 

The data then needs to be written to a queryable timeseries database like Prometheus. Dashboards would then read from that data source. I trust that your idea has value, but my suspicion is that we should treat those ideas separately.

**Comment by jgehrcke** [comment]
We also need to deploy a basic Prometheus to do the scraping, and set up a corresponding Grafana to explore/query and to build dashboards, alerts. Maybe deploy this into the k8s cluster that also runs Conbench?

**Comment by austin3dickey** [comment]
I fleshed out the conbench-on-conbench idea in https://github.com/conbench/conbench/issues/606. I agree that this ticket is a completely different scope of work.

**Comment by jgehrcke** [comment]
Path forward likely entails:
- Deploy Prometheus and Grafana on the conbench k8s via https://github.com/prometheus-operator/kube-prometheus (it's the standard, we used it exhaustively in our opstrace product).
- Monitor conbench: tackle the multi-process gunicorn challenge with the help of https://github.com/prometheus/client_python#multiprocess-mode-eg-gunicorn (per-process metrics might be weird, aggregation across all processes however imposes limits -- no silver bullet, but decision required).

Might also be a good opportunity to explore changing the request processing concurrency model. Exploring single-process multi-thread (GIL-locked to 1 CPU core) is I think a super valid option. Conbench will however always have to do a little bit of CPU work here and there, so it might turn out that it is important that individual HTTP requests can be processed truly simultaneously by more than 1 CPU core at the same time. Monitoring helps making these decisions.

**Comment by jgehrcke** [comment]
(quick brain dump largely for myself)

While slowly turning chaos into structure this here becomes more and more important. It's a boring dependency in the sense that it's never truly logically required, but it's an exciting dependency in the sense that it will allow for informed decision-making in the future, and it will allow for celebrating _wins_. Without doubt, it's industry standard to monitor a web application / API server for errors and latency.

So, whenever I think about things like performance and robustness in the context of Conbench I also think of _this_ here as the foundation.

I think prometheus-operator/kube-prometheus running side-by-side with Conbench on the same k8s is the right way to go for prod. But this also means that we need a way to develop this locally, and a way to test this in CI. For this, minikube is always a great choice.

This requires quite a bit of activation energy to be useful. As a first step towards _enabling_ this kind of capability here there is a bit of work to do. I right now have the following ideas around that:

- [x] build a proof of concept which conbench running locally on minikube
- [x] this needs postgres on k8s. this can be a timesink. need a working solution. I think https://postgres-operator.readthedocs.io/en/latest/quickstart/ with `./run_operator_locally.sh` might be that. that even launches a minikube instance (sets up the operator, does all the heavy lifting for persistent volumes, etc)
- [x] use great docs: https://postgres-operator.readthedocs.io/en/latest/user/, chapter `Connect to PostgreSQL`. 
- [x] then build a conbench makefile-powered workflow to deploy conbench on that same minikube (w/ postgres).
- [x] then run prometheus-operator/kube-prometheus on the same minikube, do basic configuration thereof for (k8s) system metrics
- [x] verify that conbench itself works
- [x] verify that grafana ui loads, and that there is a data source exposing k8s system metrics -- loads k8s monitoring dashboards

The above is **milestone 1**. Once that is done it means that a lot of the wires are in the right place, and we can continue.

**Milestone 2:**

- [x] Do very basic instrumentation of conbench, expose HTTP endpoints so that prom can scrape us
- [x] Update k8s manifests so that kube-prometheus starts scraping conbench. This uses `ServiceMonitor` from the Prometheus Operator, a custom resource.

**Milestone 3:**

Carry this to CI.

- [x] Cover all of the above more or less cleanly in CI via minikube, in its own step.
- [x] Confirm that Conbench metrics are scraped (confirm via access log analysis).

**Milestone 4:**

Work with CI support.

- [x] Build a super simple Grafana dashboard showing incoming Conbench metrics.
- [x] Make it so that this dashboard is defined in the conbench repo and integrates with kube-prometheus. https://github.com/conbench/conbench/pull/694 
- [x] Clean up / build Makefile-supported workflow for:
    - clone repo
    - `make awesome-command` 
    - open browser tab: conbench
    - open another browser tab: grafana, with simple dashboard.
- [x] Document this workflow. https://github.com/conbench/conbench/pull/706

**Milestone 5:**

Work with CI support, build PoC for custom metrics.

- [x] Add a few simple and useful custom metrics to the Conbench web application: https://github.com/conbench/conbench/pull/717
- [x] Add dashboard panels corresponding to these new metrics: https://github.com/conbench/conbench/pull/722

**Milestone 6:**

Carry this to our prod deployments:

- [ ] Adjust the k8s manifest files that we use to deploy to GKE/EKS to _also_ spawn prometheus-operator/kube-prometheus using the tested configuration
- [ ] Make it so that the Grafana UI gets exposed (static credentials are fine). Expose the Grafana UI using the same ingress, but a certain path prefix? (do not expose the Prometheus HTTP API through ingress)

**Milestone 7:**

- [ ] Build a more useful Grafana dashboard showing error rates, duration histogram, etc. Initial stab at https://github.com/conbench/conbench/pull/722.


**Milestone 8:**

An important next step is to [remote_write](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) (a special Prometheus _push_ protocol) into a separate, independent system for more independent monitoring, alerting, and retention (long-term storage). Because up until here the setup is rather ephemeral in the sense that once the conbench k8s disappears (for whichever reason), the monitoring data is also gone.

Grafana Cloud is able to be on the receiving end of the Prometheus remote_write push protocol, and provides a hopefully hassle-free/reliable monitoring and alerting solution.

(Datadog can not easily be the receiving end of the Prometheus remote_write push protocol; it is not really embracing the open source ecosystem w.r.t. interfaces and protocols).

When writing to a remote system for long-term storage provided by an external vendor we need mechanisms for cost control:
- an allowlist for which metrics to forward
- a mechanism that deduplicates metrics when sent from an HA Prometheus setup.

This milestone 8 also has its own gh issue here: https://github.com/conbench/conbench/issues/737.

Patches that work into that direction:
- https://github.com/conbench/conbench/pull/738
- https://github.com/conbench/conbench/pull/740

**Comment by jgehrcke** [comment]
More brainstorming about this:

> an important next step would be to remote_write (a special Prometheus push protocol) into a separate, independent system for more independent monitoring, alerting, and retention.

I have googled for a while, especially with `Datadog "remote_write"`, and I did not find documentation showing that one can indeed remote_write into Datadog. That was a bit of a surprise, but it's also kind of good news. Datadog doesn't seem to be the ideal platform to ingest the metrics we talk about here.

Grafana Cloud is able to receive metrics being pushed to it with the Prometheus `remote_write` protocol:

> To get Prometheus metrics into Grafana Cloud, configure Prometheus to push scraped samples using `remote_write`

(https://grafana.com/docs/grafana-cloud/data-configuration/metrics/metrics-prometheus/)

They even have OKish docs for how to integrate with technology chosen above: kube-prometheus (in particular, Prometheus Operator). But yeah these docs are not really needed because of standard tooling using standard interfaces. What's needed is this spec here:

https://github.com/prometheus-operator/prometheus-operator/blob/c0baa01acd516ffc26fe8cd5763c0eaa0cd93c88/Documentation/api.md#remotewritespec

**Comment by jgehrcke** [comment]
On the topic of pushing metrics out of a conbench k8s cluster into a system for retention, reliability, actual monitoring, alerting.

Helpful / related
- https://github.com/prometheus-operator/kube-prometheus/discussions/1855
- https://github.com/prometheus-operator/kube-prometheus/discussions/1483
- https://github.com/prometheus-operator/kube-prometheus/issues/1998

https://grafana.com/blog/2019/10/03/deduping-ha-prometheus-samples-in-cortex/
https://grafana.com/docs/grafana-cloud/data-configuration/metrics/metrics-prometheus/#sending-data-from-multiple-high-availability-prometheus-instances
https://github.com/prometheus-operator/prometheus-operator/issues/5011
https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure/prometheus-high-availability-ha/
https://grafana.com/docs/grafana-cloud/kubernetes-monitoring/other-methods/prometheus/remote_write_prometheus/

**Comment by jgehrcke** [comment]
Towards exposing Grafana via ingress controller, some ideas:
https://kubernetes.io/docs/concepts/services-networking/ingress/#simple-fanout

**Comment by jgehrcke** [comment]
Closing this here as 'done'. This is great.

There are ideas expressed in here that maybe have not been acted upon, but the main ideas certainly are done. Let's track more work in this regime with other tickets.
